version: '3.8'
services:
    nginx:
        container_name: nginx
        build:
            dockerfile: docker/images/nginx/Dockerfile
            context: .
        volumes:
            - ./:/app:cached
        environment:
            - NGINX_SERVER_NAME=localhost
        working_dir: /app
        ports:
            - '80:80'
        links:
            - php

    php:
        container_name: php
        build:
            dockerfile: docker/images/php/Dockerfile
            context: .
        volumes:
            - ./:/app:cached
            - ~/.composer:/root/.composer:delegated
        working_dir: /app
